name: "Deslop"
description: "Run @ivy-apps/deslop from NPM — check for issues or apply fixes and open a PR"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  gemini-api-key:
    description: "Gemini API key for Deslop (e.g. next-intl translations). Optional; use an invalid placeholder if not needed."
    required: false
    default: ""
  version:
    description: "NPM version of @ivy-apps/deslop (e.g. '1.2.3', '1', or 'latest'). Pin to a specific version for predictable results."
    required: false
    default: "0.4.8"
  mode:
    description: "Run mode: 'check' reports errors and may fail; 'fix' applies changes and opens a PR."
    required: false
    default: "check"
  args:
    description: "Extra arguments passed to the Deslop CLI (optional)."
    required: false
    default: ""

outputs:
  pull-request-number:
    description: "Pull request number (fix mode only, when a PR was created or updated)."
  pull-request-url:
    description: "Pull request URL (fix mode only, when a PR was created or updated)."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Create Deslop secrets config
      shell: bash
      run: |
        mkdir -p "$HOME/.deslop"
        node -e "
        const key = process.env.GEMINI_API_KEY || 'invalid';
        require('fs').writeFileSync(
          process.env.HOME + '/.deslop/secrets.json',
          JSON.stringify({ geminiApiKey: key }, null, 2)
        );
        "
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}

    - name: Run Deslop (check)
      if: inputs.mode == 'check'
      shell: bash
      run: |
        npx --yes @ivy-apps/deslop@${{ inputs.version }} --check ${{ inputs.args }}

    - name: Run Deslop (fix)
      if: inputs.mode == 'fix'
      shell: bash
      run: |
        npx --yes @ivy-apps/deslop@${{ inputs.version }} ${{ inputs.args }}

    - name: Create Pull Request with fixes
      if: inputs.mode == 'fix'
      id: cpr
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: "chore: apply Deslop fixes"
        branch: deslop-fixes-${{ github.ref_name }}
        title: "Apply Deslop fixes (into ${{ github.ref_name }})"
        body: |
          Automated fixes from [Deslop](https://www.npmjs.com/package/@ivy-apps/deslop).
          Please review the changes before merging.

    - name: Set action outputs
      if: inputs.mode == 'fix' && steps.cpr.outputs.pull-request-number != ''
      shell: bash
      run: |
        echo "pull-request-number=${{ steps.cpr.outputs.pull-request-number }}" >> "$GITHUB_OUTPUT"
        echo "pull-request-url=${{ steps.cpr.outputs.pull-request-url }}" >> "$GITHUB_OUTPUT"
