# Copy this file to your repo as .github/workflows/deslop-check.yaml
#
# Runs Deslop in check mode on every push and pull request to main.
# The job fails if Deslop reports issues (exit code 1).

name: Deslop Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deslop:
    runs-on: ubuntu-latest
    steps:
      - uses: ivy-apps/deslop-action@v1
        with:
          mode: check
