# Copy this file to your repo as .github/workflows/deslop-fix.yaml
#
# Triggers:
# 1. Manual: Actions tab → Deslop Fix → Run workflow.
# 2. PR comment: comment "@deslop fix" on a PR to run fixes on that PR's branch;
#    the action will comment on that PR with a link to the fix PR.
#
# Required: In repo Settings → Actions → General, set "Workflow permissions"
# to "Read and write permissions".

name: Deslop Fix

on:
  workflow_dispatch:

  issue_comment:
    types: [created, edited]

jobs:
  deslop-fix:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'issue_comment' ||
      (github.event.issue.pull_request != '' && contains(github.event.comment.body, '@deslop fix'))
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ivy-apps/deslop-action@v1
        with:
          mode: fix
          triggering-pr-number: ${{ github.event_name == 'issue_comment' && github.event.issue.number || '' }}
          # Optional: for next-intl translations, add a repo secret (e.g. GEMINI_API_KEY) and use:
          # gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
