# Copy this file to your repo as .github/workflows/deslop-fix.yaml
#
# Runs Deslop in fix mode when triggered manually (Actions tab → Run workflow).
# Applies fixes, then opens a PR (branch: deslop-fixes) targeting the branch
# that was checked out when the workflow ran.
#
# Required: In repo Settings → Actions → General, set "Workflow permissions"
# to "Read and write permissions".

name: Deslop Fix

on:
  workflow_dispatch:

jobs:
  deslop-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ivy-apps/deslop-action@v1
        with:
          mode: fix
          # Optional: for next-intl translations, add a repo secret (e.g. GEMINI_API_KEY) and use:
          # gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
